/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made
 * to this file will be overwritten if the respective MCUXpresso Config Tools is
 * used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: LPC55S69
package_id: LPC55S69JBD64
mcu_data: ksdk2_0
processor_version: 25.06.10
pin_labels:
- {pin_num: '42', pin_signal: PIO1_3/SCT0_OUT4/HS_SPI_MISO/USB0_PORTPWRN/PLU_OUT6, label: GREEN_LED, identifier: BOARD_;BOARD_LED_GREEN_GPIO_PIN;GREEN_LED}
- {pin_num: '39', pin_signal: PIO1_1/FC3_RXD_SDA_MOSI_DATA/CT_INP3/SCT_GPI5/HS_SPI_SSEL1/USB1_OVERCURRENTN/PLU_OUT4, label: RED_LED, identifier: BOARD_LED_RED_GPIO_PIN;RED_LED}
- {pin_num: '41', pin_signal: PIO1_2/CTIMER0_MAT3/SCT_GPI6/HS_SPI_SCK/USB1_PORTPWRN/PLU_OUT5, label: BLUE_LED, identifier: BLUE_LED}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "pin_mux.h"
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iocon.h"

/* FUNCTION
 * ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END
 * ****************************************************************************************************************/
void BOARD_InitBootPins(void) { BOARD_InitPins(); }

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '50', peripheral: USBFSH, signal: USB_VBUS, pin_signal: PIO0_22/FC6_TXD_SCL_MISO_WS/UTICK_CAP1/CT_INP15/SCT0_OUT3/USB0_VBUS/SD1_D0/PLU_OUT7/SECURE_GPIO0_22,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '59', peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO0_29/FC0_RXD_SDA_MOSI_DATA/SD1_D2/CTIMER2_MAT3/SCT0_OUT8/CMP0_OUT/PLU_OUT2/SECURE_GPIO0_29,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '60', peripheral: FLEXCOMM0, signal: TXD_SCL_MISO_WS, pin_signal: PIO0_30/FC0_TXD_SCL_MISO_WS/SD1_D3/CTIMER0_MAT0/SCT0_OUT9/SECURE_GPIO0_30, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '42', peripheral: GPIO, signal: 'PIO1, 3', pin_signal: PIO1_3/SCT0_OUT4/HS_SPI_MISO/USB0_PORTPWRN/PLU_OUT6, identifier: GREEN_LED, direction: OUTPUT,
    gpio_init_state: 'true'}
  - {pin_num: '39', peripheral: GPIO, signal: 'PIO1, 1', pin_signal: PIO1_1/FC3_RXD_SDA_MOSI_DATA/CT_INP3/SCT_GPI5/HS_SPI_SSEL1/USB1_OVERCURRENTN/PLU_OUT4, identifier: RED_LED,
    direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '41', peripheral: GPIO, signal: 'PIO1, 2', pin_signal: PIO1_2/CTIMER0_MAT3/SCT_GPI6/HS_SPI_SCK/USB1_PORTPWRN/PLU_OUT5, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION
 * ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical
 * features.
 *
 * END
 * ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitPins(void) {
  /* Enables the clock for the I/O controller.: Enable Clock. */
  CLOCK_EnableClock(kCLOCK_Iocon);

  /* Enables the clock for the GPIO0 module */
  CLOCK_EnableClock(kCLOCK_Gpio0);

  /* Enables the clock for the GPIO1 module */
  CLOCK_EnableClock(kCLOCK_Gpio1);

  gpio_pin_config_t RED_LED_config = {.pinDirection = kGPIO_DigitalOutput,
                                      .outputLogic = 1U};
  /* Initialize GPIO functionality on pin PIO1_1 (pin 39)  */
  GPIO_PinInit(BOARD_INITPINS_RED_LED_GPIO, BOARD_INITPINS_RED_LED_PORT,
               BOARD_INITPINS_RED_LED_PIN, &RED_LED_config);

  gpio_pin_config_t BLUE_LED_config = {.pinDirection = kGPIO_DigitalOutput,
                                       .outputLogic = 1U};
  /* Initialize GPIO functionality on pin PIO1_2 (pin 41)  */
  GPIO_PinInit(BOARD_INITPINS_BLUE_LED_GPIO, BOARD_INITPINS_BLUE_LED_PORT,
               BOARD_INITPINS_BLUE_LED_PIN, &BLUE_LED_config);

  gpio_pin_config_t GREEN_LED_config = {.pinDirection = kGPIO_DigitalOutput,
                                        .outputLogic = 1U};
  /* Initialize GPIO functionality on pin PIO1_3 (pin 42)  */
  GPIO_PinInit(BOARD_INITPINS_GREEN_LED_GPIO, BOARD_INITPINS_GREEN_LED_PORT,
               BOARD_INITPINS_GREEN_LED_PIN, &GREEN_LED_config);

  gpio_pin_config_t RS485_DE_config = {.pinDirection = kGPIO_DigitalOutput,
                                       .outputLogic = 0U};
  /* Initialize GPIO functionality on pin PIO0_20 */
  GPIO_PinInit(GPIO, 0U, 20U, &RS485_DE_config);

  const uint32_t port0_pin22_config =
      (/* Pin is configured as USB0_VBUS */
       IOCON_PIO_FUNC7 |
       /* No addition pin function */
       IOCON_PIO_MODE_INACT |
       /* Standard mode, output slew rate control is enabled */
       IOCON_PIO_SLEW_STANDARD |
       /* Input function is not inverted */
       IOCON_PIO_INV_DI |
       /* Enables digital function */
       IOCON_PIO_DIGITAL_EN |
       /* Open drain is disabled */
       IOCON_PIO_OPENDRAIN_DI);
  /* PORT0 PIN22 (coords: 50) is configured as USB0_VBUS */
  IOCON_PinMuxSet(IOCON, 0U, 22U, port0_pin22_config);

  const uint32_t port0_pin13_config =
      (/* Pin is configured as FC1_RXD_SDA_MOSI_DATA */
       IOCON_PIO_FUNC1 |
       /* No addition pin function */
       IOCON_PIO_MODE_INACT |
       /* Standard mode, output slew rate control is enabled */
       IOCON_PIO_SLEW_STANDARD |
       /* Input function is not inverted */
       IOCON_PIO_INV_DI |
       /* Enables digital function */
       IOCON_PIO_DIGITAL_EN |
       /* Open drain is disabled */
       IOCON_PIO_OPENDRAIN_DI |
       /* Disable I2C specific filter/slew to allow standard digital output */
       IOCON_GPIO_MODE);
  /* PORT0 PIN13 is configured as FC1_RXD_SDA_MOSI_DATA */
  IOCON_PinMuxSet(IOCON, 0U, 13U, port0_pin13_config);

  const uint32_t port0_pin14_config =
      (/* Pin is configured as FC1_TXD_SCL_MISO_WS */
       IOCON_PIO_FUNC1 |
       /* No addition pin function */
       IOCON_PIO_MODE_INACT |
       /* Standard mode, output slew rate control is enabled */
       IOCON_PIO_SLEW_STANDARD |
       /* Input function is not inverted */
       IOCON_PIO_INV_DI |
       /* Enables digital function */
       IOCON_PIO_DIGITAL_EN |
       /* Open drain is disabled */
       IOCON_PIO_OPENDRAIN_DI |
       /* Disable I2C specific filter/slew to allow standard digital output */
       IOCON_GPIO_MODE);
  /* PORT0 PIN14 is configured as FC1_TXD_SCL_MISO_WS */
  IOCON_PinMuxSet(IOCON, 0U, 14U, port0_pin14_config);

  const uint32_t port0_pin20_config =
      (/* Pin is configured as PIO0_20 */
       IOCON_PIO_FUNC0 |
       /* No addition pin function */
       IOCON_PIO_MODE_INACT |
       /* Standard mode, output slew rate control is enabled */
       IOCON_PIO_SLEW_STANDARD |
       /* Input function is not inverted */
       IOCON_PIO_INV_DI |
       /* Enables digital function */
       IOCON_PIO_DIGITAL_EN |
       /* Open drain is disabled */
       IOCON_PIO_OPENDRAIN_DI);
  /* PORT0 PIN20 is configured as PIO0_20 */
  IOCON_PinMuxSet(IOCON, 0U, 20U, port0_pin20_config);

  IOCON->PIO[1][1] = ((IOCON->PIO[1][1] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                      /* Selects pin function.
                       * : PORT11 (pin 39) is configured as PIO1_1. */
                      | IOCON_PIO_FUNC(PIO1_1_FUNC_ALT0)

                      /* Select Digital mode.
                       * : Enable Digital mode.
                       * Digital input is enabled. */
                      | IOCON_PIO_DIGIMODE(PIO1_1_DIGIMODE_DIGITAL));

  IOCON->PIO[1][2] = ((IOCON->PIO[1][2] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                      /* Selects pin function.
                       * : PORT12 (pin 41) is configured as PIO1_2. */
                      | IOCON_PIO_FUNC(PIO1_2_FUNC_ALT0)

                      /* Select Digital mode.
                       * : Enable Digital mode.
                       * Digital input is enabled. */
                      | IOCON_PIO_DIGIMODE(PIO1_2_DIGIMODE_DIGITAL));

  IOCON->PIO[1][3] = ((IOCON->PIO[1][3] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                      /* Selects pin function.
                       * : PORT13 (pin 42) is configured as PIO1_3. */
                      | IOCON_PIO_FUNC(PIO1_3_FUNC_ALT0)

                      /* Select Digital mode.
                       * : Enable Digital mode.
                       * Digital input is enabled. */
                      | IOCON_PIO_DIGIMODE(PIO1_3_DIGIMODE_DIGITAL));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
